### ISSUE TITLE
Handle multiple approve

### ISSUE THREAD

**Issue by irony** [Klimatbyran/garbo#333]
![Image](https://github.com/user-attachments/assets/b16ad64c-1fdc-4872-bf4c-40cacf13cbdf)

**Comment by Greenheart** [comment]
Based on the log in BullMQ from these interactions, it seems like perhaps multiple workers try to handle the same job, even after it has already been finished.

> Error: Job 24 is not in the active state. moveToFinished
>     at Scripts.finishedErrors (/app/node_modules/bullmq/src/classes/scripts.ts:1480:16)
>     at Scripts.moveToFinished (/app/node_modules/bullmq/src/classes/scripts.ts:605:18)
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async Job.moveToCompleted (/app/node_modules/bullmq/src/classes/job.ts:653:20)
>     at async handleCompleted (/app/node_modules/bullmq/src/classes/worker.ts:839:31)
>     at async <anonymous> (/app/node_modules/bullmq/src/classes/worker.ts:905:18)
>     at async DiscordWorker.retryIfFailed (/app/node_modules/bullmq/src/classes/worker.ts:1175:16)
